global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['0.0.0.0:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    params:
      format: [prometheus]